name: Release

on:
  push:
    tags:
      - v*

jobs:
  build-jvm:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Build JVM jar and embedded jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1

      - name: Generate jar and embedded jar
        run: lein with-profile native-image uberjar

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Rename jar
        run: mv target/sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag}}-standalone.jar sqlite-graalvm-sample.jar

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          path: sqlite-graalvm-sample.jar
          name: sqlite-graalvm-sample.jar

  native-linux:
    name: Build native linux binary
    needs: build-jvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build Linux native image
        env:
          SQLITE_GRAALVM_SAMPLE_JAR: sqlite-graalvm-sample.jar
          SQLITE_GRAALVM_SAMPLE_XMX: "-J-Xmx6g"
        run: |
          graalvm/native-unix-compile.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: sqlite-graalvm-sample
          name: sqlite-graalvm-sample-native-linux-amd64.zip

  native-static-linux:
    name: Build native static linux binary
    needs: build-jvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build static Linux native image
        env:
          SQLITE_GRAALVM_SAMPLE_JAR: sqlite-graalvm-sample.jar
          SQLITE_GRAALVM_SAMPLE_XMX: "-J-Xmx6g"
          SQLITE_GRAALVM_SAMPLE_STATIC: true
        run: |
          graalvm/native-unix-compile.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: sqlite-graalvm-sample
          name: sqlite-graalvm-sample-native-static-linux-amd64.zip

  native-macos:
    name: Build native MacOS binary
    needs: build-jvm
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build MacOS native image
        env:
          SQLITE_GRAALVM_SAMPLE_JAR: sqlite-graalvm-sample.jar
          SQLITE_GRAALVM_SAMPLE_XMX: "-J-Xmx6g"
        run: |
          graalvm/native-unix-compile.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: sqlite-graalvm-sample
          name: sqlite-graalvm-sample-native-macos-amd64.zip

  native-windows:
    name: Build native Windows binary
    needs: build-jvm
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu.cmd install native-image

      - name: Build Windows native image
        env:
          SQLITE_GRAALVM_SAMPLE_JAR: sqlite-graalvm-sample.jar
          SQLITE_GRAALVM_SAMPLE_XMX: "-J-Xmx6g"
        run: |
          .\graalvm\native-windows-compile.bat

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: sqlite-graalvm-sample.exe
          name: sqlite-graalvm-sample-native-windows-amd64.zip

  release:
    name: Create Release
    needs: [build-jvm, native-linux, native-macos, native-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest-tag.outputs.tag}}
          release_name: ${{ steps.latest-tag.outputs.tag}}

  upload-to-release:
    name: Upload artifacts to release
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload JVM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample.jar
          asset_name: sqlite-graalvm-sample.jar
          tag: ${{ steps.latest-tag.outputs.tag}}

      - name: Upload Linux native binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-native-linux-amd64.zip
          asset_name: sqlite-graalvm-sample-native-linux-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag }}

      - name: Upload static Linux native binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-native-static-linux-amd64.zip
          asset_name: sqlite-graalvm-sample-native-static-linux-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag }}

      - name: Upload MacOS native binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-native-macos-amd64.zip
          asset_name: sqlite-graalvm-sample-native-macos-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag}}

      - name: Upload Windows native binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-native-windows-amd64.zip
          asset_name: sqlite-graalvm-sample-native-windows-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag}}
