name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest-tag.outputs.tag}}
          release_name: ${{ steps.latest-tag.outputs.tag}}

  build-jvm:
    name: Build JVM jar and embedded jar
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - name: Generate jar and embedded jar
        run: lein with-profiles +native-image uberjar

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          path: target/sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag}}-standalone.jar
          name: sqlite-graalvm-sample.jar

  deploy-native-linux:
    name: Deploy native linux binary
    needs: build-jvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build Linux native image
        run: |
          export SQLITE_GRAALVM_SAMPLE_JAR=sqlite-graalvm-sample.jar
          export SQLITE_GRAALVM_SAMPLE_XMX="-J-Xmx6g"
          graalvm/native-compile.sh

      - uses: papeloto/action-zip@v1
        with:
          files: sqlite-graalvm-sample
          dest: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-linux-amd64.zip

      - name: Upload native image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-linux-amd64.zip
          asset_name: sqlite-graalvm-sample-native-linux-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag}}

  deploy-native-mac:
    name: Deploy native MacOS binary
    needs: build-jvm
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Build MacOS native image
        run: |
          export SQLITE_GRAALVM_SAMPLE_JAR=sqlite-graalvm-sample.jar
          export SQLITE_GRAALVM_SAMPLE_XMX="-J-Xmx6g"
          graalvm/native-compile.sh

      - uses: papeloto/action-zip@v1
        with:
          files: sqlite-graalvm-sample
          dest: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-macos-amd64.zip

      - name: Upload native image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-macos-amd64.zip
          asset_name: sqlite-graalvm-sample-native-macos-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag}}

  deploy-native-static-linux:
    name: Deploy native static linux binary
    needs: build-jvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu install native-image

      - name: Display structure of downloaded files
        run: ls -lR

      - name: Build Linux native image
        run: |
          export SQLITE_GRAALVM_SAMPLE_JAR=sqlite-graalvm-sample.jar
          export SQLITE_GRAALVM_SAMPLE_XMX="-J-Xmx6g"
          export SQLITE_GRAALVM_SAMPLE_STATIC=true
          graalvm/native-compile.sh

      - uses: papeloto/action-zip@v1
        with:
          files: sqlite-graalvm-sample
          dest: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-static-linux-amd64.zip

      - name: Upload native image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-static-linux-amd64.zip
          asset_name: sqlite-graalvm-sample-native-static-linux-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag}}

  deploy-native-windows:
    name: Deploy native Windows binary
    needs: build-jvm
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: sqlite-graalvm-sample.jar

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.5

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install native-image component
        run: |
          gu.cmd install native-image

      - name: Display structure of downloaded files
        run: ls -lR

      - name: Build Windows native image
        run: |
          export SQLITE_GRAALVM_SAMPLE_JAR=sqlite-graalvm-sample.jar
          export SQLITE_GRAALVM_SAMPLE_XMX="-J-Xmx6g"
          graalvm/native-compile.sh

      - uses: papeloto/action-zip@v1
        with:
          files: sqlite-graalvm-sample
          dest: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-windows-amd64.zip

      - name: Upload native image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sqlite-graalvm-sample-${{ steps.latest-tag.outputs.tag }}-windows-amd64.zip
          asset_name: sqlite-graalvm-sample-native-windows-amd64.zip
          tag: ${{ steps.latest-tag.outputs.tag}}
